name: Bug Report
description: Report a bug or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug or issue?
      placeholder: Describe the bug or issue. What is happening?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: List the steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The expected outcome.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, version, and any other relevant environment info.
      placeholder: e.g. macOS 14.1, cedardb version
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or log files here.
      placeholder: Optional
    validations:
      required: false
