name: Compatibility Request
description: Suggest a new feature or bug regarding PostgreSQL compatibility (e.g., pg-specific functions or tables).
title: "[Compatibility]: "
labels: ["compatibility"]
type: "Compatibility"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug or missing compatibility feature! Please provide as much detail as possible to help us understand the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the missing PostgreSQL feature or compatibility bug.
      placeholder: A detailed description of the compatibility issue.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: List the steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve or how does it improve the project?
      placeholder: Describe the problem or situation that this would address.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots.
      placeholder: Anything else you want to add?
    validations:
      required: false
