name: Question
description: Ask a question or request clarification.
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question? Feel free to ask below — we’ll do our best to help!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question?
      placeholder: What are you trying to understand?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any context or background information that will help to answer the question.
      placeholder: Background or surrounding details (optional)
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or related links.
      placeholder: Links, screenshots, examples, etc. (optional)
    validations:
      required: false

